[package]
name = "rusty-zechub"
version = "0.1.0"
edition = "2024"

[dependencies]
bip0039 = "0.12.0"
curl = "0.4.48"
dialoguer = "0.11.0"
fs = "0.0.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
